### ISSUE TITLE
Error while using KPCA

### ISSUE THREAD

**Issue by rvaishali23** [Nikronic/Machine-Learning-Models#3]
I tried to reduce dimensionality of NSL-KDD dataset.  I'm getting the following error,
Unable to allocate 95.6 GiB for an array with shape (113270, 113270) and data type float64

why?

**Comment by Nikronic** [comment]
Hi @rvaishali23 

From the error, it could be interpreted that dataset is too large and you do not have enough memory for doing it. And the KPCA method needs to have access to all the data, so it's not possible due to memory issue.

**Comment by rvaishali23** [comment]
ok thank you
